site: Eyup Sukru Ergin's Intelligence Blog
url: https://ergin.dev
title: Eyup Sukru Ergin's Intelligence Blog
description: Welcome to my blog where I share my research on Military and Cyber ​​Threat Intelligence.
twitter:
  username: ErginDev
  card: summary
  creator: Eyup Sukru Ergin
author:
  twitter: ErginDev
  name: Eyup Sukru Ergin
  avatar: 
  email: ergindev@gmail.com
  url: https://ergin.dev/about
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-admin
  - jemoji

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
